# Centering and Scaling

In [1]:
import numpy as np

In [2]:
year = np.arange(2000, 2008)
penguins = np.array([5.49, 7.03, 7.73, 7.70, 9.29, 9.21, 11.89, 10.85])

When performing polynomial fitting with large x values, numerical precision limitations can lead to inaccurate results.

In [3]:
c = np.polyfit(year, penguins, 3)
c

array([-4.82322194e-03,  2.89752731e+01, -5.80216510e+04,  3.87279910e+07])

In [4]:
np.polyval(c, year)

array([ 5.76939379,  6.57852822,  7.43060619,  8.29668836,  9.14783548,
        9.95510812, 10.68956701, 11.32227283])

We can avoid the numerical precision limitations by centering and scaling the x data when using polyfit and polyval. 

In [5]:
year_mean, year_std = year.mean(), year.std()
c = np.polyfit((year - year_mean) / year_std, penguins, 3)
c

array([-0.05801992, -0.0771875 ,  1.95298606,  8.7259375 ])

In [6]:
np.polyval(c, (year - year_mean) / year_std)

array([ 5.76939394,  6.57852814,  7.43060606,  8.29668831,  9.1478355 ,
        9.95510823, 10.6895671 , 11.32227273])