# Monitoring Loon Populations

In [1]:
import numpy as np

In [2]:
population_change = np.array([[0, 0, 0, .145],
                              [.6, .375, 0, 0],
                              [0, .225, .56, .05],
                              [0, 0, .35, .86]])

loons = np.array([[41, 61, 52, 62]])

The current loon population is stored in the variable loons, and the population change matrix is stored in population_change.

In [3]:
loons_next_year = population_change.dot(loons.T)
loons_next_year

array([[ 8.99 ],
       [47.475],
       [45.945],
       [71.52 ]])

The loon population is aging, and the total number of loons went down. We can apply matrix multiplication again to get the expected population two years from now.

In [4]:
loons_2years = population_change.dot(population_change).dot(loons.T)
loons_2years

array([[10.3704  ],
       [23.197125],
       [39.987075],
       [77.58795 ]])

In [5]:
population_change_60years = np.linalg.matrix_power(population_change, 60)
population_change_60years

array([[0.0006748 , 0.00105719, 0.00265471, 0.00288226],
       [0.0007166 , 0.00112267, 0.00281916, 0.00306081],
       [0.0009999 , 0.00156651, 0.00393369, 0.00427087],
       [0.00437456, 0.00685348, 0.01720986, 0.018685  ]])

In [6]:
loons_60years = population_change_60years.dot(loons.T)
loons_60years

array([[0.40890024],
       [0.43423017],
       [0.60589937],
       [2.65080219]])

Create a vector of target loon populations.

In [7]:
loon_goal = np.array([[9, 50, 50, 75]])

With this model, it looks like the loon population will die out. If a target loon population is given, stored in the variable loon_goal, let's calculate the starting population needed to get us there in a year. This is equivalent to solving population_change∗x = loon_goal for a vector of initial populations, x.
To solve a system of linear equations, Ax=B, we can use the [solve()](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html#numpy-linalg-solve) function.

In [8]:
required_population = np.linalg.solve(population_change, loon_goal.T)
required_population

array([[49.15708812],
       [54.68199234],
       [61.77339901],
       [62.06896552]])

Create a matrix whose columns are the original and trial loon populations.

In [9]:
loon_populations = np.array([[41, 110, 14, 23],
                              [61, 54, 36, 67],
                              [52, 21, 102, 81],
                              [62, 5, 153, 28]])

A matrix whose columns are the original loon population and three other theoretical starting population has been created and saved to the variable loon_populations.

In [10]:
loons_compare = population_change_60years.dot(loon_populations)
loons_compare

array([[0.40890024, 0.20147619, 0.75927229, 0.38208676],
       [0.43423017, 0.21395693, 0.80630653, 0.40575569],
       [0.60589937, 0.29854298, 1.12507295, 0.56616775],
       [2.65080219, 1.30612181, 4.92218016, 2.47697685]])