# Combining Matrices

In [1]:
import numpy as np

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
B = np.array([[1, 2], [3, 4], [5, 6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
C = np.array([[1, 2, 3], [4, np.NAN, 6], [7, 8, 9]])
C

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

We can concatenate two arrays horizontally (side-by-side) using [concatenate()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy-concatenate) if they are the same height (have an equal number of rows).

In [7]:
BC = np.concatenate((B, C), axis=1)
BC

array([[ 1.,  2.,  1.,  2.,  3.],
       [ 3.,  4.,  4., nan,  6.],
       [ 5.,  6.,  7.,  8.,  9.]])

We can concatenate two matrices vertically (stacked on top of one another) if they are the same width (have an equal number of columns).

In [8]:
CA = np.concatenate((C, A), axis=0)
CA

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.],
       [ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [11]:
CR = np.concatenate((C, np.array([[10, 11, 12]])), axis=0)
CR

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [12]:
v = np.array([[10], [11], [12]])
CC = np.concatenate((C, v), axis=1)
CC

array([[ 1.,  2.,  3., 10.],
       [ 4., nan,  6., 11.],
       [ 7.,  8.,  9., 12.]])