# Reshape a Matrix

In [1]:
import numpy as np

In [3]:
A = np.random.randint(10, size=(12, 2))
A

array([[2, 3],
       [5, 9],
       [3, 7],
       [3, 5],
       [7, 1],
       [9, 5],
       [2, 4],
       [9, 6],
       [5, 0],
       [1, 5],
       [8, 7],
       [3, 6]])

We can use the [reshape()](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy-reshape) function to reshape an m-by-n matrix into a p-by-q matrix, as long as the total number of elements remains the same (i.e., m×n = p×q).

In [4]:
B = A.reshape(8, 3)
B

array([[2, 3, 5],
       [9, 3, 7],
       [3, 5, 7],
       [1, 9, 5],
       [2, 4, 9],
       [6, 5, 0],
       [1, 5, 8],
       [7, 3, 6]])

For convenience, we can leave one of the dimensions as -1 when calling reshape and that dimension will be calculated automatically.

In [5]:
C = A.reshape(-1, 4)
C

array([[2, 3, 5, 9],
       [3, 7, 3, 5],
       [7, 1, 9, 5],
       [2, 4, 9, 6],
       [5, 0, 1, 5],
       [8, 7, 3, 6]])

We can reshape any matrix into a column vector.

In [9]:
D = A.reshape(-1, 1)
D

array([[2],
       [3],
       [5],
       [9],
       [3],
       [7],
       [3],
       [5],
       [7],
       [1],
       [9],
       [5],
       [2],
       [4],
       [9],
       [6],
       [5],
       [0],
       [1],
       [5],
       [8],
       [7],
       [3],
       [6]])

Or a  row vector.

In [11]:
E = A.reshape(1, -1)
E

array([[2, 3, 5, 9, 3, 7, 3, 5, 7, 1, 9, 5, 2, 4, 9, 6, 5, 0, 1, 5, 8, 7,
        3, 6]])