# Array Creation Functions

In [1]:
import numpy as np

The [ones()](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#) function creates an array of given shape, filled with ones.

In [3]:
x = np.ones((3, 4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
x = 5 * np.ones((3, 4))
x

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

The [rand()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html#numpy-random-rand) function creates an array of uniformly distributed random numbers. Random numbers can be useful for creating simulations.

In [7]:
xU = np.random.rand(100)
xU

array([0.47423874, 0.91773867, 0.34659436, 0.07329287, 0.74916443,
       0.70698228, 0.76829975, 0.84642516, 0.11283523, 0.0266271 ,
       0.97346946, 0.22117074, 0.32002874, 0.2131233 , 0.24379482,
       0.827874  , 0.39840248, 0.96842198, 0.60916005, 0.79067761,
       0.88698017, 0.4998799 , 0.31128862, 0.89162475, 0.82747315,
       0.89319639, 0.19947376, 0.8220211 , 0.74593057, 0.72329307,
       0.22321166, 0.08023063, 0.11950862, 0.03927099, 0.05508084,
       0.90577184, 0.76575947, 0.16672888, 0.05024562, 0.53982132,
       0.38202122, 0.10681312, 0.87848886, 0.07666685, 0.22801489,
       0.11937529, 0.81927925, 0.19367961, 0.93445263, 0.09582391,
       0.28448878, 0.29061746, 0.82374851, 0.60873985, 0.74705323,
       0.08452265, 0.55612793, 0.81634004, 0.45143012, 0.01773622,
       0.06475944, 0.21228944, 0.30108168, 0.96725413, 0.244212  ,
       0.47072741, 0.06028798, 0.04261255, 0.98109806, 0.71023147,
       0.91686842, 0.54785944, 0.08794656, 0.15322733, 0.24448

The [randn()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html#numpy-random-randn) function creates an array of normally distributed random numbers.

In [8]:
xN = np.random.randn(100)
xN

array([ 0.28840367,  0.17686495,  1.14475526,  0.32442954,  1.74229933,
       -0.36568059, -1.01275436, -0.56092342, -1.03242642,  0.70460951,
        1.06049501, -1.56287242, -0.27856358, -0.5209661 , -0.15199723,
        0.76489585,  0.35690352, -0.40818852, -0.58316559, -0.92287764,
        1.47908156,  1.56996267, -1.03764288, -2.83958552, -1.23838643,
       -1.80737727, -1.44203383,  2.39885381,  0.67421807, -0.32812357,
       -0.23456638,  1.44558333, -0.03136324, -0.65644341, -1.40122334,
        1.30127689, -0.29262123,  0.26264537,  0.17206045, -1.44045298,
        1.11944881, -0.39407171,  0.31924004,  0.2598575 ,  0.1489683 ,
       -0.68664644, -0.60787988,  1.10930716,  0.78250007,  0.72376853,
       -2.06420295,  1.72044082, -0.89704871,  0.89821112,  0.92033998,
       -1.15129007,  1.01733368,  1.11793776, -0.82248561, -0.1485592 ,
       -1.28258556,  0.60627956, -0.55024329, -0.26378307,  0.82734058,
       -0.96095691,  0.75287496,  0.47771024,  1.40619938,  1.30

The [randint()](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html#numpy-random-randint) function creates a matrix of uniformly distributed random integers.

In [10]:
xI = np.random.randint(10, size=100)
xI

array([4, 5, 9, 2, 3, 4, 7, 1, 6, 8, 4, 1, 3, 8, 6, 9, 1, 1, 0, 8, 4, 1,
       7, 2, 6, 4, 4, 6, 5, 1, 7, 9, 8, 1, 9, 2, 0, 9, 5, 1, 0, 1, 2, 6,
       4, 4, 4, 0, 3, 1, 5, 8, 3, 4, 1, 6, 9, 0, 3, 4, 7, 5, 3, 8, 7, 7,
       9, 1, 0, 4, 7, 5, 7, 3, 7, 1, 1, 4, 2, 7, 2, 3, 9, 7, 2, 6, 7, 7,
       2, 4, 9, 1, 8, 9, 4, 0, 2, 8, 8, 7])

We can specify the interval over which the random integers are distributed.

In [11]:
xI2 = np.random.randint(low=11, high=20, size=100)
xI2

array([16, 12, 16, 18, 14, 12, 13, 12, 19, 19, 12, 18, 15, 13, 14, 11, 17,
       16, 14, 16, 19, 13, 12, 18, 16, 13, 16, 18, 14, 12, 17, 11, 11, 16,
       12, 18, 17, 19, 11, 15, 16, 12, 17, 14, 17, 13, 16, 15, 12, 11, 12,
       19, 11, 15, 17, 17, 18, 14, 16, 15, 11, 15, 16, 13, 16, 12, 16, 12,
       12, 13, 12, 12, 16, 17, 11, 14, 12, 18, 14, 18, 18, 12, 11, 17, 17,
       14, 14, 12, 17, 13, 19, 14, 14, 13, 19, 14, 13, 13, 11, 19])

The uniformly distributed random numbers generated by rand lie between zero and one by default. The rand function doesn't allow us to specify the interval over which the numbers are distributed. If we want uniformly distributed numbers between values a and b, we can compute the following:

x = a + (b - a) * np.random.rand(m, n)

In [13]:
xU2 = -1 + 2 * np.random.rand(100)
xU2

array([-0.55240419, -0.58262776,  0.12368676, -0.02267668, -0.0169401 ,
       -0.02890592, -0.7073498 ,  0.7236818 , -0.05307752,  0.83411876,
       -0.99594737,  0.86503968,  0.10371275, -0.64522365,  0.02402628,
        0.75280632, -0.81523913,  0.50188735,  0.55898167,  0.05678513,
        0.6869935 ,  0.38878623,  0.2379244 , -0.21435914,  0.95942102,
        0.3594337 , -0.11472141, -0.13019774,  0.82826948,  0.88104648,
        0.02697364,  0.93314574, -0.23270096,  0.16137527,  0.63264833,
       -0.47079378,  0.58862516,  0.68186593, -0.91430546,  0.52368908,
       -0.79554725,  0.31510555,  0.50777958,  0.90350234, -0.20354437,
       -0.03730356,  0.17124327,  0.85349005, -0.55975644,  0.40051566,
        0.88690236, -0.12255936,  0.27523496, -0.7867171 , -0.88008767,
       -0.8097807 ,  0.82228185,  0.22419493,  0.09522797, -0.60662046,
        0.79314087, -0.72489731,  0.57222238,  0.37949122, -0.53649291,
       -0.67675264,  0.32077946,  0.35569371, -0.01699627, -0.76

Similarly, normally distributed random numbers generated by the randn function will have a mean of zero and a standard deviation of one by default.
If we want normally distributed numbers with mean M and standard deviation sd, you can compute the following: 

x = M + sd * np.random.randn(m, n)

In [14]:
xN2 = 100 + 5 * np.random.randn(100)
xN2

array([101.0409235 , 101.72547837, 101.52151591,  97.64595409,
        99.34918221, 100.46941927, 103.07414574,  97.73053631,
       103.67781628,  96.93451686,  90.80822106,  94.65845624,
        94.29195732, 103.09769744, 105.12043861,  97.60651311,
       100.74337164,  97.45642173, 104.45661867, 107.96041541,
       103.81094172, 100.05817269,  99.04805241,  95.03287553,
        95.67973378,  96.24263426,  97.51794638,  98.87495614,
       100.33940395,  92.5065302 ,  97.03928646, 101.34200784,
       104.5680205 ,  98.72626885, 104.49572955, 100.02778848,
       101.80880451, 100.86565465,  99.72318784,  96.64110957,
       107.00368123, 105.05945355,  96.53405765,  93.52128298,
       104.39807005,  97.47861671,  99.97292685, 101.96698065,
        98.37864418, 105.24811785, 103.96989882,  95.90500084,
        97.84776683,  97.41831538, 105.13533248,  91.35982512,
        94.97942053, 107.36453107,  94.90863545, 101.88488749,
        95.82116566, 110.51300892,  98.60430994, 104.45