# Evenly-Spaced Vectors

In [1]:
import numpy as np

Create evenly-spaced vectors using the [arange()](https://numpy.org/doc/stable/reference/generated/numpy.arange.html#numpy-arange) function.

In [8]:
x = np.arange(5, 16)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
y = np.arange(3, 12, 2)
y

array([ 3,  5,  7,  9, 11])

Descending arrays can be created using a negative spacing.

In [10]:
z = np.arange(5, 0, -1)
z

array([5, 4, 3, 2, 1])

Depending on the chosen spacing, we are not guaranteed to produce a vector that includes the end point.

In [11]:
A = np.arange(0, 13, 5)
A

array([ 0,  5, 10])

Create evenly-spaced vectors using the [linspace()](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#) function. It gaurantees that the vector will contain the starting and end points, but does not allow us to control the size of the spacing.

In [12]:
B = np.linspace(0, 1, 90)
B

array([0.        , 0.01123596, 0.02247191, 0.03370787, 0.04494382,
       0.05617978, 0.06741573, 0.07865169, 0.08988764, 0.1011236 ,
       0.11235955, 0.12359551, 0.13483146, 0.14606742, 0.15730337,
       0.16853933, 0.17977528, 0.19101124, 0.20224719, 0.21348315,
       0.2247191 , 0.23595506, 0.24719101, 0.25842697, 0.26966292,
       0.28089888, 0.29213483, 0.30337079, 0.31460674, 0.3258427 ,
       0.33707865, 0.34831461, 0.35955056, 0.37078652, 0.38202247,
       0.39325843, 0.40449438, 0.41573034, 0.42696629, 0.43820225,
       0.4494382 , 0.46067416, 0.47191011, 0.48314607, 0.49438202,
       0.50561798, 0.51685393, 0.52808989, 0.53932584, 0.5505618 ,
       0.56179775, 0.57303371, 0.58426966, 0.59550562, 0.60674157,
       0.61797753, 0.62921348, 0.64044944, 0.65168539, 0.66292135,
       0.6741573 , 0.68539326, 0.69662921, 0.70786517, 0.71910112,
       0.73033708, 0.74157303, 0.75280899, 0.76404494, 0.7752809 ,
       0.78651685, 0.79775281, 0.80898876, 0.82022472, 0.83146

linspace can also help when it is not obvious what the spacing should be between elements.

In [13]:
C = np.linspace(3 * np.pi, -np.pi, 20)
C

array([ 9.42477796,  8.76339003,  8.10200211,  7.44061418,  6.77922625,
        6.11783833,  5.4564504 ,  4.79506247,  4.13367454,  3.47228662,
        2.81089869,  2.14951076,  1.48812284,  0.82673491,  0.16534698,
       -0.49604095, -1.15742887, -1.8188168 , -2.48020473, -3.14159265])