# Accessing Data in Matrices

In [1]:
import numpy as np

In [2]:
M = np.array([[9, 7, 10, 10, 5], 
              [10, 1, 10, 5, 10], 
              [2, 3, 2, 9, 8], 
              [0, 6, 10, 2, 10]])
M

array([[ 9,  7, 10, 10,  5],
       [10,  1, 10,  5, 10],
       [ 2,  3,  2,  9,  8],
       [ 0,  6, 10,  2, 10]])

Extract elements from M.

In [3]:
M_small = M[1:3, [1, 3]]
M_small

array([[1, 5],
       [3, 9]])

In [4]:
M_inside = M[1:-1, 1:-1]
M_inside

array([[ 1, 10,  5],
       [ 3,  2,  9]])

In [5]:
M_corners = M[np.ix_((0, -1), (0, -1))]
M_corners

array([[ 9,  5],
       [ 0, 10]])