# Comparisons with Arrays

In [1]:
import numpy as np

In [2]:
x = np.random.randint(20, size=(3, 5))
x

array([[ 5,  0,  0, 17, 17],
       [ 5, 12, 16,  4,  6],
       [17,  2,  8, 12,  0]])

In [3]:
y = np.random.randint(20, size=(3, 5))
y

array([[15,  3, 16, 12, 14],
       [ 2, 19,  8,  6, 18],
       [14, 19,  3, 12,  3]])

In [4]:
u = np.random.randint(20, size=(3, 1))
u

array([[3],
       [7],
       [2]])

In [5]:
v = np.random.randint(20, size=(1, 5))
v

array([[12, 13, 17,  1,  5]])

We can use relational operators to compare each element of an array with a scalar value.

In [6]:
z = x > 8
z

array([[False, False, False,  True,  True],
       [False,  True,  True, False, False],
       [ True, False, False,  True, False]])

When we use a relational operator with two arrays, the operation is applied to each element of the arrays and the result is an array the same size as the input arrays.

In [7]:
z2 = x < y
z2

array([[ True,  True,  True, False, False],
       [False,  True, False,  True,  True],
       [False,  True, False, False,  True]])

Logical operators also work element-wise, so the operation is applied to each element and the result is an array the same size as the input arrays.

In [8]:
z3 = z & z2
z3

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [9]:
w = (x > 12) | (y >= 6)
w

array([[ True, False,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True, False,  True, False]])

We can also compare each row or column of a matrix to a vector.

In [10]:
a = x >= v
a

array([[False, False, False,  True,  True],
       [False, False, False,  True,  True],
       [ True, False, False,  True, False]])

The logical operators & and | also respect the same expansion rules.

In [11]:
b = a & (u > 8)
b

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])