# Operations on Logical Arrays

In [1]:
import numpy as np

In [2]:
x = np.random.randint(20, size=(3, 4))
x

array([[13, 18, 13, 18],
       [ 5,  1,  8,  9],
       [ 9, 11,  6,  9]])

In [3]:
x5 = x > 5
x5

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

The any and all functions accept an optional dimension argument to specify which dimension to act on.

In [4]:
column_all = x5.all(axis=0)
column_all

array([False, False,  True,  True])

In [5]:
row_all = x5.all(axis=1)
row_all

array([ True, False,  True])

The sum function always acts on the entire array. That is, it returns the total number of non-zero elements in the array, regardless of the shape of the array.

In [6]:
x5_sum = x5.sum()
x5_sum

10

Recall that true and false are logical values equivalent to 1 and 0, respectively. If we perform any mathematical operation on a logical variable, it will automatically be converted to a numerical variable (with values of 0 or 1). This means we can use statistical functions on logical arrays. Summing logical values is equivalent to counting the true (1) values.

In [7]:
column_sum = x5.sum(axis=0)
column_sum

array([2, 2, 3, 3])

We can perform any mathematical operation on logical arrays, as if they were arrays of 0s and 1s, with all the usual rules of array arithmetic applying.

In [8]:
two_or_three = 3 - x5
two_or_three

array([[2, 2, 2, 2],
       [3, 3, 2, 2],
       [2, 2, 2, 2]])