# Standardize Missing Values

In [1]:
import numpy as np

In [2]:
x = np.array([2, np.nan, 5, 3, -999, 4, np.nan, 0, 8, -999, 3, np.nan, 8])
x

array([   2.,   nan,    5.,    3., -999.,    4.,   nan,    0.,    8.,
       -999.,    3.,   nan,    8.])

Missing data may be represented in multiple ways, such as error codes like -999.

In [3]:
idx = np.isnan(x)
idx

array([False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False])

By default, isnan finds only NaN values in a numeric array. However, we can replace any value with NaN.

In [4]:
x[x == -999] = np.nan
x

array([ 2., nan,  5.,  3., nan,  4., nan,  0.,  8., nan,  3., nan,  8.])

In [5]:
idx = np.isnan(x)
idx

array([False,  True, False, False,  True, False,  True, False, False,
        True, False,  True, False])