# Removing Missing Data

In [1]:
import numpy as np

In [2]:
z = np.random.rand(50, 4)
z[z > 0.97] = np.nan
z

array([[0.84224336, 0.34366679, 0.0715907 , 0.82587297],
       [0.81533429, 0.27888707, 0.57518648, 0.02624631],
       [0.53669101, 0.23267936, 0.88012832, 0.11809455],
       [0.10449792, 0.83435878, 0.65116686, 0.8592963 ],
       [0.06840798, 0.0868804 , 0.33690761, 0.41137845],
       [0.73408583, 0.10105541, 0.02380438, 0.30748816],
       [0.67211007, 0.2776169 , 0.74500593, 0.46797478],
       [0.19371423, 0.24164954, 0.91551993, 0.27908003],
       [0.73123758, 0.57033383, 0.20190718, 0.30201781],
       [0.07562997, 0.51895274, 0.64457296, 0.83788439],
       [0.24117697, 0.52719227, 0.38029028, 0.83140397],
       [0.19153128, 0.73906604, 0.37385904, 0.91141978],
       [0.46049859, 0.41816043,        nan, 0.53723499],
       [0.50138563, 0.40638835, 0.03007418, 0.91693543],
       [0.45773931, 0.87928691, 0.23346633, 0.00995412],
       [0.40234848, 0.19618994, 0.92444812, 0.67915532],
       [0.08241073,        nan, 0.55932178, 0.42710451],
       [0.27740939, 0.74233571,

Remove the rows with missing data.

In [3]:
clean_z = z[~np.isnan(z).any(axis=1), :]
clean_z

array([[0.84224336, 0.34366679, 0.0715907 , 0.82587297],
       [0.81533429, 0.27888707, 0.57518648, 0.02624631],
       [0.53669101, 0.23267936, 0.88012832, 0.11809455],
       [0.10449792, 0.83435878, 0.65116686, 0.8592963 ],
       [0.06840798, 0.0868804 , 0.33690761, 0.41137845],
       [0.73408583, 0.10105541, 0.02380438, 0.30748816],
       [0.67211007, 0.2776169 , 0.74500593, 0.46797478],
       [0.19371423, 0.24164954, 0.91551993, 0.27908003],
       [0.73123758, 0.57033383, 0.20190718, 0.30201781],
       [0.07562997, 0.51895274, 0.64457296, 0.83788439],
       [0.24117697, 0.52719227, 0.38029028, 0.83140397],
       [0.19153128, 0.73906604, 0.37385904, 0.91141978],
       [0.50138563, 0.40638835, 0.03007418, 0.91693543],
       [0.45773931, 0.87928691, 0.23346633, 0.00995412],
       [0.40234848, 0.19618994, 0.92444812, 0.67915532],
       [0.27740939, 0.74233571, 0.45584022, 0.23164647],
       [0.51384298, 0.29403593, 0.25865541, 0.52643177],
       [0.14390309, 0.77404493,

Remove missing entries from vectors.

In [4]:
x = np.array([2, np.nan, 5, 4, np.nan])
clean_x = x[~np.isnan(x)]
clean_x

array([2., 5., 4.])